[versions]
dagger = "2.38.1"

[libraries]
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1"
androidCore = "androidx.core:core-ktx:1.6.0"
viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"
fragment = "androidx.fragment:fragment-ktx:1.4.0-alpha03"
appcompat = "androidx.appcompat:appcompat:1.3.0"
material = "com.google.android.material:material:1.4.0"
constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.0"
coil = "io.coil-kt:coil:1.3.1"
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

junit = "junit:junit:4.13.2"
androidJunit = "androidx.test.ext:junit:1.1.3"
espresso = "androidx.test.espresso:espresso-core:3.4.0"